name: PSITS Client

on:
  pull_request:
    branches:
      - master
      - production

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Locate Client-side Directory
        run: ls -la client-side

      - name: Setup Node and Build Project
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: client-side/package-lock.json

      - name: Install Dependencies
        run: npm install
        working-directory: client-side

      - name: Build Project
        run: npm run build
        working-directory: client-side
